// <auto-generated />
using System;
using FiscalMiddleware.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiscalMiddleware.Infrastructure.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    [Migration("20260717230533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FiscalMiddleware.Domain.Entities.HistoricoProcessamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetalheErro")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long>("DuracaoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("MotivoFalha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusAlcancado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tentativa")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TransacaoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("UltimoStatusHttp")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.ToTable("HistoricosProcessamento", (string)null);
                });

            modelBuilder.Entity("FiscalMiddleware.Domain.Entities.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Lotes", (string)null);
                });

            modelBuilder.Entity("FiscalMiddleware.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChaveIdempotencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CnpjEmitente")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("DocumentoFiscal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadOriginal")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveIdempotencia");

                    b.HasIndex("LoteId");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("FiscalMiddleware.Domain.Entities.HistoricoProcessamento", b =>
                {
                    b.HasOne("FiscalMiddleware.Domain.Entities.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transacao");
                });

            modelBuilder.Entity("FiscalMiddleware.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("FiscalMiddleware.Domain.Entities.Lote", "Lote")
                        .WithMany("Transacoes")
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lote");
                });

            modelBuilder.Entity("FiscalMiddleware.Domain.Entities.Lote", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
